name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    strategy:
      matrix:
        include:
          - name: "Windows Server 2022 + Visual Studio 2022"
            os: windows-2022

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure Build
      run: mkdir build && cd build && cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release ..
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: cd build && MSBuild.exe Mizu.sln /p:Configuration=Release